// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY7R_DmAnOinzCB4XcZ-r4H3XNyDqX6xY',
    appId: '1:281283958415:web:2d361018dc51e85e2a82fa',
    messagingSenderId: '281283958415',
    projectId: 'chromser-d72db',
    authDomain: 'chromser-d72db.firebaseapp.com',
    databaseURL: 'https://chromser-d72db.firebaseio.com',
    storageBucket: 'chromser-d72db.appspot.com',
    measurementId: "G-QDJX1DEK4J"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3jokcD6H7l9FVe56w1uE9W2s2J4dgKW0',
    appId: '1:281283958415:android:e410e007ac4216982a82fa',
    messagingSenderId: '281283958415',
    projectId: 'chromser-d72db',
    databaseURL: 'https://chromser-d72db.firebaseio.com',
    storageBucket: 'chromser-d72db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARN20M_u0h9cg0ZFzGMkfJjQusXw-ZYX8',
    appId: '1:281283958415:ios:16ec0e63ec14a02e2a82fa',
    messagingSenderId: '281283958415',
    projectId: 'chromser-d72db',
    databaseURL: 'https://chromser-d72db.firebaseio.com',
    storageBucket: 'chromser-d72db.appspot.com',
    androidClientId: '281283958415-507jm533l8fmn1v34160o8gkkd7n5m99.apps.googleusercontent.com',
    iosClientId: '281283958415-24ln2rg276il7fhee3q57jaiq8k7olga.apps.googleusercontent.com',
    iosBundleId: 'com.example.Chromser',
  );
}
