const FOOD_DATA = [
  {
    "index":0,
    "name":"Social Media",
    "brand":"Facebook",
    "price":4,
    "image":"social_media.png"
  },{
    "index":1,
    "name":"Shopping",
    "brand":"Amazon",
    "price":4,
    "image":"shoppin.jpg"
  },
  {
    "index":2,
    "name":"Streaming",
    "brand":"Youtube",
    "price":5,
    "image":"streaming.png"
  },
  {
    "index":3,
    "name":"Payment",
    "brand":"Paypal",
    "price":3,
    "image":"payment.png"
  },
  {
    "index":4,
    "name":"Games",
    "brand":"Birds",
    "price":3,
    "image":"games.png"
  },
  {
    "index":5,
    "name":"Calling",
    "brand":"Polic",
    "price":5,
    "image":"calling.png"
  },
  {
    "index":6,
    "name":"Chat",
    "brand":"Original",
    "price":4,
    "image":"chat.png"
  },
  {
    "index":7,
    "name":"Programmers",
    "brand":"Github",
    "price":5,
    "image":"programmers.png"
  },
  {
    "index":8,
    "name":"Trading",
    "brand":"Groww",
    "price":4,
    "image":"trading.png"
  }
];